# This file was generated by GoReleaser. DO NOT EDIT.
cask "castor" do
  name "castor"
  desc "Cast video streams to networked devices"
  homepage ""
  version "0.0.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "castor"

  on_macos do
    on_intel do
      url "https://github.com/stupside/castor/releases/download/v#{version}/castor_#{version}_darwin_amd64.tar.gz"
      sha256 "aa9c70299f4e0dd57dfa2905290323ed11a308f8f51ada3434e9c07ca7e407cb"
    end
    on_arm do
      url "https://github.com/stupside/castor/releases/download/v#{version}/castor_#{version}_darwin_arm64.tar.gz"
      sha256 "ce2734220556c61bb41d0fd7adf785f5ee1750a65c1b638da7672f46db8dcd95"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/stupside/castor/releases/download/v#{version}/castor_#{version}_linux_amd64.tar.gz"
      sha256 "f99edf7076bb18fd22271b7b4e5577abff34851889e6a3acdc9aab5ccc3c743d"
    end
    on_arm do
      url "https://github.com/stupside/castor/releases/download/v#{version}/castor_#{version}_linux_arm64.tar.gz"
      sha256 "9a4f17ff7658c32d718fb5b6fe3dbe2d0eb596b1c7c6e08862563e13ce7aed59"
    end
  end

  zap delete: [
      "~/.castor/config.yml",
    ],
    trash: [
      "~/.castor/config.yml",
    ]

end
