# This file was generated by GoReleaser. DO NOT EDIT.
cask "castor" do
  name "castor"
  desc "Cast video streams to networked devices"
  homepage ""
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "castor"

  on_macos do
    on_intel do
      url "https://github.com/stupside/castor/releases/download/v#{version}/castor_#{version}_darwin_amd64.tar.gz"
      sha256 "36a8aba4fce7c20b39de3268674e97ce28a9d1cc7807af2f5c5f3dd9095823d4"
    end
    on_arm do
      url "https://github.com/stupside/castor/releases/download/v#{version}/castor_#{version}_darwin_arm64.tar.gz"
      sha256 "7d01235902903e746bddd5d718128224fbbefbfb185966bb22ac86ceea82c970"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/stupside/castor/releases/download/v#{version}/castor_#{version}_linux_amd64.tar.gz"
      sha256 "c51033009e11b140126657d18b57e3009fde6bf0854ddf3756da471643526555"
    end
    on_arm do
      url "https://github.com/stupside/castor/releases/download/v#{version}/castor_#{version}_linux_arm64.tar.gz"
      sha256 "903ff5de7101e44c47639fbdd330e909bb45f40a9b392adb4b3915aa842c7e26"
    end
  end

  zap delete: [
      "~/.castor/config.yml",
    ],
    trash: [
      "~/.castor/config.yml",
    ]

end
