# This file was generated by GoReleaser. DO NOT EDIT.
cask "castor" do
  name "castor"
  desc "Cast video streams to networked devices"
  homepage ""
  version "0.0.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "castor"

  on_macos do
    on_intel do
      url "https://github.com/stupside/castor/releases/download/v#{version}/castor_#{version}_darwin_amd64.tar.gz"
      sha256 "f908918a9bab3c88ba437c006b49cdf007c4608c71df71f058f23e7fa0b64c06"
    end
    on_arm do
      url "https://github.com/stupside/castor/releases/download/v#{version}/castor_#{version}_darwin_arm64.tar.gz"
      sha256 "0f10e83765be85b1dcf555b1488341bbd15e1b43ca4d2fe54eb5af748c8a3ada"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/stupside/castor/releases/download/v#{version}/castor_#{version}_linux_amd64.tar.gz"
      sha256 "3ac6b047ce3776f821b7473b0ff7aa90d9227e2bc8cdc3992e29333b8b238ecb"
    end
    on_arm do
      url "https://github.com/stupside/castor/releases/download/v#{version}/castor_#{version}_linux_arm64.tar.gz"
      sha256 "d744345c691c84629cbd71bd7cd8e4d28fb0b1479c73d2bf4e623e6c9b50c80a"
    end
  end

  zap delete: [
      "~/.castor/config.yml",
    ],
    trash: [
      "~/.castor/config.yml",
    ]

end
