# This file was generated by GoReleaser. DO NOT EDIT.
cask "moley" do
  desc "Expose your local apps to the world—securely, instantly, and with zero hassle."
  homepage ""
  version "1.1.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "moley"

  on_macos do
    on_intel do
      url "https://github.com/stupside/moley/releases/download/v1.1.2/moley_1.1.2_darwin_amd64.tar.gz"
      sha256 "6d35a8eb7c511fd8969e9e14a708405e76c1b893de784fc9003dea9f542d4ef6"
    end
    on_arm do
      url "https://github.com/stupside/moley/releases/download/v1.1.2/moley_1.1.2_darwin_arm64.tar.gz"
      sha256 "4e0481675ac355ca6ba8e962efa675299f6ed3673de81d81b09a7655bf99b163"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/stupside/moley/releases/download/v1.1.2/moley_1.1.2_linux_amd64.tar.gz"
      sha256 "b8fab1097aacac710f8eb4f7fe22add4c8911c8c99117a3dff8dbfe841c015cc"
    end
    on_arm do
      url "https://github.com/stupside/moley/releases/download/v1.1.2/moley_1.1.2_linux_arm64.tar.gz"
      sha256 "928104ab9a6bc9d1d85ee87db56bb461651d8b35d5cccd9f50fa759a8bfffaf1"
    end
  end

  zap delete: [
      "~/.moley/config.yml",
    ],
    trash: [
      "~/.moley/config.yml",
    ]

end
