# This file was generated by GoReleaser. DO NOT EDIT.
cask "moley" do
  version "2.5.1"

  on_macos do
    on_intel do
      url "https://github.com/stupside/moley/releases/download/v#{version}/moley_#{version}_darwin_amd64.tar.gz"
      sha256 "90fae9256cbefe0880f50add3f3e889ee964aea499004ca11d89f01166903243"
    end
    on_arm do
      url "https://github.com/stupside/moley/releases/download/v#{version}/moley_#{version}_darwin_arm64.tar.gz"
      sha256 "d8361c0b83ccc60f68b506b5fd83b2fe15aed86cda823cbc959935e78b78c5b8"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/stupside/moley/releases/download/v#{version}/moley_#{version}_linux_amd64.tar.gz"
      sha256 "9cfad9c9c5c5f06acaf969f8f6d6bea204425a34a0e80b9e0cb864de9700449f"
    end
    on_arm do
      url "https://github.com/stupside/moley/releases/download/v#{version}/moley_#{version}_linux_arm64.tar.gz"
      sha256 "0a6266da4fdc45763e431c94b1a2de366b7f944f554bb883e00b17ce5023cc9f"
    end
  end

  name "moley"
  desc "Expose your local apps to the world—securely, instantly, and with zero hassle."
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "moley"

  zap delete: [
      "~/.moley/config.yml",
    ],
    trash: [
      "~/.moley/config.yml",
    ]

end
